/**
 * ==========================================================
 * LÉLUVERSE
 * GENESIS EVENTS
 * ==========================================================
 */

export enum GenesisEvent {

  CORE_BIRTH = "CORE_BIRTH",

  CHAOS_SURGE = "CHAOS_SURGE",

  ENERGY_SURGE = "ENERGY_SURGE",

  MATTER_FORMED = "MATTER_FORMED",

  STAR_BORN = "STAR_BORN",

  PLANET_FORMED = "PLANET_FORMED",

  LIFE_CREATED = "LIFE_CREATED",

  CIVILIZATION_CREATED = "CIVILIZATION_CREATED",

  MEMORY_CREATED = "MEMORY_CREATED",

  TEACHING_STARTED = "TEACHING_STARTED",

  SIMULATION_STARTED = "SIMULATION_STARTED",

  DIMENSION_CHANGED = "DIMENSION_CHANGED",

  CONSCIOUSNESS_EXPANDED = "CONSCIOUSNESS_EXPANDED",

}