/**
 * ==========================================================
 * LÉLUVERSE
 * ECOSYSTEM VISUALIZER
 *
 * Renders the living biosphere generated by
 * EcosystemSystem.
 * ==========================================================
 */

import { useFrame } from "@react-three/fiber";

import { useMemo, useRef } from "react";

import { Group } from "three";

import { useGenesis } from "../GenesisCore";

export default function EcosystemVisualizer() {

  const { state } = useGenesis();

  const shell = useRef<Group>(null);

  const life = useRef<Group>(null);

  const timer = useRef(0);

  const organisms = useMemo(
    () => Array.from({ length: 180 }),
    [],
  );

  useFrame((_, delta) => {

    timer.current += delta;

    if (
      !shell.current ||
      !life.current
    ) {
      return;
    }

    const ecosystem =
      (state as any).ecosystem ?? {};

    const vegetation =
      ecosystem.vegetation ?? 0.5;

    const biodiversity =
      ecosystem.biodiversity ?? 0.5;

    const health =
      ecosystem.health ?? 1;

    shell.current.scale.setScalar(

      1 +

      Math.sin(
        timer.current * 0.45
      ) *

      vegetation *

      0.05

    );

    shell.current.rotation.y +=

      delta *

      (0.05 + biodiversity * 0.15);

    life.current.rotation.y -=

      delta *

      (0.08 + biodiversity * 0.2);

    life.current.rotation.z =

      Math.sin(
        timer.current * 0.3
      ) *

      0.05 *

      health;

  });

  return (

    <group ref={shell}>

      <mesh>

        <sphereGeometry
          args={[
            3.9,
            64,
            64,
          ]}
        />

        <meshBasicMaterial
          color="#66ff99"
          transparent
          opacity={0.03}
        />

      </mesh>

      <group ref={life}>

        {

          organisms.map((_, i) => (

            <mesh
              key={i}
              position={[

                Math.sin(i * 1.37) * 3,

                Math.cos(i * 2.11) * 2.2,

                Math.sin(i * 0.83) * 3,

              ]}

            >

              <sphereGeometry
                args={[
                  0.02 + (i % 5) * 0.01,
                  10,
                  10,
                ]}
              />

              <meshBasicMaterial
                color="#55ff88"
                transparent
                opacity={0.4}
              />

            </mesh>

          ))

        }

      </group>

      <pointLight
        color="#66ff99"
        intensity={6}
        distance={40}
      />

    </group>

  );

}